linters:
    StringQuotes:
        enabled: false
    HexNotation:
        style: uppercase
    PropertySortOrder:
        enabled: false
    QualifyingElement:
        enabled: false
    SingleLinePerProperty:
        enabled: false
    SingleLinePerSelector:
        enabled: false
    NestingDepth:
        max_depth: 5
    SelectorDepth:
        max_depth: 5
    Indentation:
        enabled: false
